nome = str(input('digite seu nome completo:')).strip()
print('seu nome em maicusula fica:{} ' .format (nome.upper()))
print ('seu nome em minuscula fica: {} '.format(nome.lower()))
print ('seu nome tem {} letras '.format(len(nome) - nome.count(' ')))
print ('seu primeiro nome tem {} letras' .format(nome.find(' ')))